---
- name: Create/copy main SSSD config file from template
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
  notify:
    - restart sssd

- name: Create/copy idmapd.conf from template
  template:
    src: idmapd.conf.j2
    dest: /etc/idmapd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart idmapd

- name: Push ldap.conf from template
  template:
    src: ldap.conf.j2
    dest: "{{ldap_dir}}/ldap.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart sssd
    - restart idmapd
