---
- name: Ensure rpc.idmapd is started and enabled on boot
  service:
    name: "{{ idmapd_daemon }}"
    state: "{{ idmapd_service_state }}"
    enabled: "{{ idmapd_service_enabled }}"

- name: Ensure SSSD is started and enabled on boot
  service:
    name: "{{ sssd_daemon }}"
    state: "{{ sssd_service_state }}"
    enabled: "{{ sssd_service_enabled }}"
