---
# handlers file for sssd configuration
- name: restart sssd
  service:
    name: "{{ sssd_daemon }}"
    state: "{{ sssd_restarted_state }}"

- name: restart idmapd
  service:
    name: "{{ idmapd_daemon }}"
    state: "{{ idmapd_restarted_state }}"
